trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# NOTE: requires a Linux build agent

- task: DEV-SOOS-Security-Analysis@0
  displayName: Security Analysis
  continueOnError: true
  inputs:
    clientId: zwzksilww
    apiKey: YmFhNjRlZDQtZTM1NC00MGUzLTk4M2YtMDNhNjRlNDQzMzgz
    baseUri: https://qa-api.soos.io/api/
    scanType: 'CSA'
    projectName: "AzureDevOps - Container"
    targetToScan: debian
    logLevel: INFO
    dockerImageTag: beta
    verbose: true


