trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# NOTE: requires a Linux build agent

- task: SOOS-Security-Analysis@0
  displayName: Security Analysis
  continueOnError: true
  inputs:
    clientId: oczlfuebe
    apiKey: MWIzYjIwMzgtNzc5NC00ZmI2LWIyZjAtMmYxZDhkMzY4ZjI3
    baseUri: https://qa-api.soos.io/api/
    scanType: 'CSA'
    projectName: "AzureDevOps - Container 11"
    targetToScan: debian
    logLevel: DEBUG
    onFailure: FAIL_THE_BUILD
    dockerImageTag: alpha


